config/routes.rb
Blocitoff::Application.routes.draw do
  get "static/index"
  resources :task_items

  devise_for :users
  resources :task_items, only: [:new, :create, :show]

  root 'static#index'

end

app/models/task_item.rb
class TaskItem < ActiveRecord::Base
  belongs_to :user

   def days_left
    7 - (Time.now.day - created_at.day)
  end

  def self.mine(user_id)
    all.where(user_id: user_id)
  end

end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :task_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    task_items_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def index
  end
end

app/controllers/task_items_controller.rb
class TaskItemsController < ApplicationController
  before_action :set_task_item, only: [:show, :edit, :update, :destroy]

  # GET /task_items
  # GET /task_items.json
  def index
    @task_items = TaskItem.mine(current_user.id)
  end

  # GET /task_items/1
  # GET /task_items/1.json
  def show
  end

  # GET /task_items/new
  def new
    @task_item = TaskItem.new
  end

  # GET /task_items/1/edit
  def edit
  end

  # POST /task_items
  # POST /task_items.json
  def create
    @task_item = TaskItem.new(task_item_params)
    @task_item.user_id = current_user.id


    respond_to do |format|
      if @task_item.save
        format.html { redirect_to task_items_path, notice: 'Task item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @task_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @task_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_items/1
  # PATCH/PUT /task_items/1.json
  def update
    respond_to do |format|
      if @task_item.update(task_item_params)
        format.html { redirect_to task_items_path, notice: 'Task item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_items/1
  # DELETE /task_items/1.json
  def destroy
    @task_item.destroy
    respond_to do |format|
      format.html { redirect_to task_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_item
      @task_item = TaskItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_item_params
      params.require(:task_item).permit(:name, :user_id)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to @todo, notice: 'Your new TODO was saved'
  end

  def show
    @todo = Todo.find params[:id]
  end


  private

  def todo_params
    params.require(:todo).permit(:description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/task_items_helper.rb
module TaskItemsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <ul>
  <ul class="nav nav-tabs">
    <li><%= link_to("Register", :new_user_registration)%></li>
    <li><%= current_user ? link_to("Sign Out", :destroy_user_session, method: "DELETE") : link_to("Sign In", :new_user_session) %></li>
    
  </ul>

  <p><%= flash[:notice] if flash[:notice] %></p>
  <p><%= flash[:alert] if flash[:alert] %></p>

<%= yield %>
</div>
</body>
</html>

app/views/task_items/_form.html.erb
<%= form_for(@task_item) do |f| %>
  <% if @task_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_item.errors.count, "error") %> prohibited this task_item from being saved:</h2>

      <ul>
      <% @task_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <form role="form">
    <div class="col-md-8">
      <div class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter todo" %>
      </div>
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
</form>
</br>
<% end %>

app/views/task_items/edit.html.erb
<h1>Editing task_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_item %> |
<%= link_to 'Back', task_items_path %>

app/views/task_items/index.html.erb
<h1 align="center">My Todos</h1>

<table class="table table-striped table-bordered table-responsive">
  <thead>
    <tr>
      <th>Description</th>
      <th>Days Left</th>
      <th>Edit</th>
      <th>Complete</th>
    </tr>
  </thead>

  <tbody>
    <% @task_items.each do |task_item| %>
      <tr>
        <td><%= task_item.name %></td>
        <td><%= task_item.days_left%></td>
        <td><%= link_to 'Edit', edit_task_item_path(task_item) %></td>
        <td><%= link_to 'Complete', task_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_task_item_path %>

app/views/task_items/new.html.erb
<h1>Create New Todo</h1>

<%= render 'form' %>

<%= link_to 'Back', task_items_path %>

app/views/task_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task_item.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @task_item.user_id %>
</p>

<%= link_to 'Edit', edit_task_item_path(@task_item) %> |
<%= link_to 'Back', task_items_path %>

app/views/todos/new.html.erb
<%= form_for @todo do |form| %>
<%= form.text_field :description, placeholder: 'Description' %>
<%= form.submit 'Save' %>
<% end %>

app/views/todos/show.html.erb
<p><b><%= @todo.description %></b></p>